# Generated by Django 4.2.13 on 2024-05-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_customerorder_total_price_vehicle_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerorder",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerorder",
            name="order",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="CustomerOrder",
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
