# Generated by Django 4.2.13 on 2024-05-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_vehicle_color_vehicle_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorder",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="number_in_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("unicycle", "Unicycle"),
                    ("bicycle", "Bicycle"),
                    ("tricycle", "Tricycle"),
                ],
                max_length=20,
            ),
        ),
    ]
