# Generated by Django 4.2.13 on 2024-05-17 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0006_customerorder_total_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerorder",
            name="order",
        ),
        migrations.RemoveField(
            model_name="customerorder",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="number_in_stock",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("unicycle", "Unicycle"),
                    ("bicycle", "Bicycle"),
                    ("tricycle", "Tricycle"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.customerorder",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_app.vehicle"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customerorder",
            name="vehicles",
            field=models.ManyToManyField(
                through="my_app.OrderItem", to="my_app.vehicle"
            ),
        ),
    ]
